### ISSUE TITLE
Protocol version 5.2 not supported

### ISSUE THREAD

**Issue by debjan** [fiber-space/jupyter-kernel-jsr223#11]
I get this error:

```
[jupyter-kernel.jar] python kernel started.
Exception in thread "Thread-0" java.lang.RuntimeException: [jupyter-kernel] Protocol version 5.2not supported by this kernel
        at org.jupyterkernel.kernel.MessageObject.checkAllowedProtocolVersion(MessageObject.java:106)
        at org.jupyterkernel.kernel.MessageObject.read(MessageObject.java:176)
        at org.jupyterkernel.kernel.Kernel.dispatch(Kernel.java:136)
        at org.jupyterkernel.kernel.Session.run(Session.java:239)
```

**Comment by bdw429s** [comment]
@debjan Did you get this to work?  I'm trying to use this kernel now and I've getting the same error, but just for protocol version 5.3.  

@fiber-space any chance of getting this fixed?

**Comment by debjan** [comment]
unfortunately not, thou I didn't try too hard, as this is not the only kernel that can't cope with jupyter dev

**Comment by bdw429s** [comment]
Thanks for the reply @debjan .  I did try bypassing the version check, but then then ran into other issues with the communication.  It seems the newer versions of the protocol do need explicit support added.

**Comment by fiber-space** [comment]
Protocol version 5.3 is now supported. Message structures have changed very little but Jupyter sends now a comm_info_request at startup which wasn't handled yet. I also removed a dependency on javax/xml/bind/DatatypeConverter which caused some trouble in Java 9.

**Comment by bdw429s** [comment]
Thanks for your work on this @fiber-space , I'll give this another shot and try to load up Lucee Server.

**Comment by bdw429s** [comment]
Hi @fiber-space , it's still not working for me on the latest version:

```
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.jupyterkernel.json.messages.T_JSON.toJSON(T_JSON.java:149)
        at org.jupyterkernel.json.messages.T_JSON.toJSON(T_JSON.java:149)
        at org.jupyterkernel.kernel.MessageObject.send(MessageObject.java:192)
        at org.jupyterkernel.kernel.Kernel.dispatch(Kernel.java:173)
        at org.jupyterkernel.kernel.Session.run(Session.java:239)
```

**Comment by bdw429s** [comment]
I created a new issue here: https://github.com/fiber-space/jupyter-kernel-jsr223/issues/15
