### ISSUE TITLE
System classloader no longer URL classloader on Java 9

### ISSUE THREAD

**Issue by bdw429s** [fiber-space/jupyter-kernel-jsr223#13]
```
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at org.jupyterkernel.console.InteractiveConsole.getClasses(InteractiveConsole.java:53)
        at org.jupyterkernel.console.InteractiveConsole.<init>(InteractiveConsole.java:74)
        at org.jupyterkernel.console.ConsoleFactory.createConsole(ConsoleFactory.java:36)
        at org.jupyterkernel.kernel.Kernel.<init>(Kernel.java:107)
        at org.jupyterkernel.kernel.Session.setKernel(Session.java:201)
        at org.jupyterkernel.kernel.Session.runKernel(Session.java:283)
        at org.jupyterkernel.kernel.Session.main(Session.java:326)
```

**Comment by fiber-space** [comment]
I removed that call and just print the classpath now if no script engine can be found for some kernel name.
