### ISSUE TITLE
NPE after interactive console starts

### ISSUE THREAD

**Issue by bdw429s** [fiber-space/jupyter-kernel-jsr223#15]
I compiled the very latest version of the kernel that supports protocol 5.3 but I get this error as soon as my kernel starts.

```
[jupyter-kernel.jar] CFML kernel started.
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.jupyterkernel.json.messages.T_JSON.toJSON(T_JSON.java:149)
        at org.jupyterkernel.json.messages.T_JSON.toJSON(T_JSON.java:149)
        at org.jupyterkernel.kernel.MessageObject.send(MessageObject.java:192)
        at org.jupyterkernel.kernel.Kernel.dispatch(Kernel.java:173)
        at org.jupyterkernel.kernel.Session.run(Session.java:239)
```

**Comment by opeongo** [comment]
What language are you using?  The method `getKernelInfo` in the default `InteractiveConsole` does not properly instantiate the `T_kernel_info_reply` and this is what is leading to the NPE.  You may have to create an override of this class for your language.

**Comment by bdw429s** [comment]
I was using Lucee Server (CFML). I  haven't really looked at this project in 5 years though.  I gave up :)
