### ISSUE TITLE
Protocol 5.1 not supported

### ISSUE THREAD

**Issue by cloudgen** [fiber-space/jupyter-kernel-jsr223#7]
I've started jupyter and failed with the following message:

java.lang.RuntimeException: [jupyter-kernel] Protocol version 5.1not supported by this kernel
	at org.jupyterkernel.kernel.MessageObject.checkAllowedProtocolVersion(MessageObject.java:106)
	at org.jupyterkernel.kernel.MessageObject.read(MessageObject.java:176)
	at org.jupyterkernel.kernel.Kernel.dispatch(Kernel.java:136)
	at org.jupyterkernel.kernel.Session.run(Session.java:239)

**Comment by fiber-space** [comment]
I haven't reviewed the latest changes in the Jupyter messaging protocol yet but I will soon upgrade the kernel implementation to support 5.1. Fortunately I already cared in advance for versioning and protocol changes, so I expect that this goes quickly.

**Comment by bdw429s** [comment]
@cloudgen Did you get this to work?  I'm trying to use this kernel now and I've getting the same error, but just for protocol version 5.3.  

@fiber-space any chance of getting this fixed?

**Comment by fiber-space** [comment]
I will examine if the check on the protocol number is actually needed. I might have been overly defensive at the time of the first release. I hope I find some time at the end of next week to close this issue.

Von meinem iPad gesendet

**Comment by bdw429s** [comment]
@fiber-space Thank you for the reply.  To let you know what I'm trying to do-- my goal is to get a CFML (ColdFusion) kernel running.  Lucee Server is an open source CFML engine (JVM based) which supports JSR-223 which seems like a great match for what you've done here.  I played with your code a bit and just commented out the version check but then I hit several other errors.  Null pointer exceptions in the JSON converter and unhandled message types, which may be related to the new protocol version.  Also, the classloader issues in Java 9+ which I documented in a new ticket.  All of this may be very easy to fix but I'm not familiar with Jupyter at all so I'm not sure where to start,
